apiVersion: v1
kind: Service
metadata:
    name: "jlcluster-5577"
    labels:
        app: "jlcluster-5577"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "jlcluster-5577"