on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: juncontainerregistry.azurecr.io
        username: ${{ secrets.acr_juncontainerregistry_username }}
        password: ${{ secrets.acr_juncontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/testContext" -f  "test" -t juncontainerregistry.azurecr.io/jlcluster:${{ github.sha }} --label dockerfile-path=test
        docker push juncontainerregistry.azurecr.io/jlcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jlcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: juncontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_juncontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_juncontainerregistry_password }}
        secret-name: jlclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          juncontainerregistry.azurecr.io/jlcluster:${{ github.sha }}
        imagepullsecrets: |
          jlclusterdockerauth
